# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/fastai_models',
                'doc_host': 'https://goutamgaraidev.github.io',
                'git_url': 'https://github.com/goutamgaraidev/fastai_models',
                'lib_path': 'fastai_models'},
  'syms': {'fastai_models.core': {'fastai_models.core.foo': ('core.html#foo', 'fastai_models/core.py')}}}