# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_fastai_models.ipynb.

# %% auto 0
__all__ = ['say_hello']

# %% ../nbs/01_fastai_models.ipynb 2
from fastcore.test import *
from IPython.display import display,SVG

# %% ../nbs/01_fastai_models.ipynb 3
def say_hello(to):
    "Say hello to somebody"
    return f'Hello {to}!'
